create table app_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(120) not null
);

create table bank_account (
    id bigint generated by default as identity primary key,
    account_number varchar(16) not null unique,
    balance numeric(19,2) not null check (balance >= 0),
    owner_id bigint not null references app_user(id),
    version bigint not null default 0
);

create table ledger_entry (
    id bigint generated by default as identity primary key,
    account_id bigint not null references bank_account(id),
    entry_type varchar(24) not null,
    amount numeric(19,2) not null check (amount > 0),
    counterparty_account varchar(16),
    occurred_at timestamp with time zone not null
);

create index idx_ledger_account_time on ledger_entry(account_id, occurred_at desc);
